app:
  name: "Authorization Service"
  env: "dev"
  port: 8888
  id: "1"
  keys-server: "https://zon9zfmig8.execute-api.us-east-1.amazonaws.com/dev"
newrelic:
  enabled: false
  apikey: "apikey~tmp"
  ignorehttpcodes: [400, 401, 402, 403, 404, 405, 406]
mssql:
  connection:
    host: "host~tmp"
    port: 12345
    database: "db~tmp"
    user: "user~tmp"
    password: "pwd~tmp"